# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160825_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_cat',
            new_name='ParentCategory',
        ),
        migrations.AddField(
            model_name='category',
            name='RSSItem',
            field=models.ManyToManyField(to='api.RSSItem'),
        ),
        migrations.AddField(
            model_name='category',
            name='Reader',
            field=models.ManyToManyField(to='api.Reader'),
        ),
    ]
